name: Update Draft HIPs Data

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours
  workflow_dispatch:        # Allows manual triggering

jobs:
  update-draft-hips:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Create Test Script
        run: |
          mkdir -p _data
          cat << 'EOF' > fetch-draft-hips.js
          const https = require('https');

          const query = `
            query { 
              repository(name: "hedera-improvement-proposal", owner: "hashgraph") {
                pullRequests(first: 100, orderBy: {field: CREATED_AT, direction: DESC}, states: [OPEN]) {
                  nodes {
                    title
                    number
                    url
                    headRefOid
                    files(last: 100) {
                      edges {
                        node {
                          path
                          additions
                          deletions
                        }
                      }
                    }
                    author {
                      login
                    }
                  }
                }
              }
            }
          `;

          const options = {
            hostname: 'api.github.com',
            path: '/graphql',
            method: 'POST',
            headers: {
              'Authorization': `Bearer ${process.env.GITHUB_TOKEN}`,
              'Content-Type': 'application/json',
              'User-Agent': 'Node.js'
            }
          };

          const req = https.request(options, (res) => {
            let data = '';
            
            res.on('data', (chunk) => {
              data += chunk;
            });
            
            res.on('end', () => {
              const result = JSON.parse(data);
              if (result.errors) {
                console.error('GraphQL errors:', result.errors);
                process.exit(1);
              }
              
              // Log stats for verification
              console.log('API Response Status:', res.statusCode);
              console.log('Number of PRs fetched:', result.data.repository.pullRequests.nodes.length);
              console.log('Sample of file counts:', result.data.repository.pullRequests.nodes.slice(0,3).map(pr => ({
                pr: pr.number,
                files: pr.files.edges.length
              })));
              
              const fs = require('fs');
              fs.writeFileSync('_data/draft_hips.json', JSON.stringify(result.data.repository.pullRequests.nodes, null, 2));
            });
          });

          req.on('error', (error) => {
            console.error('Error:', error);
            process.exit(1);
          });

          req.write(JSON.stringify({ query }));
          req.end();
          EOF

      - name: Run Script
        run: node fetch-draft-hips.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and Push Changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add _data/draft_hips.json
          git commit -m "Update draft HIPs data [skip ci]"
          git push origin main